version: '3'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresql:
    image: postgres:13
    volumes:
      - ../initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=back
      - POSTGRES_PASSWORD=back
    ports:
      - "5432:5432"
    restart: always
